// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TreeTrack.Server.Data;

#nullable disable

namespace TreeTrack.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619120000_AddProjectSharing")]
    partial class AddProjectSharing
    {
    }
}
