// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeTrack.Server.Data;

#nullable disable

namespace TreeTrack.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616191148_AddIssues")]
    partial class AddIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TreeTrack.Server.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentIssueId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentIssueId");

                    b.HasIndex("ProjectId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assignee = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete overhaul of the authentication system including OAuth, SSO, and role-based access control.",
                            DueDate = new DateOnly(2026, 4, 30),
                            IssueNumber = 1,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Authentication & User Management",
                            Type = "Epic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Assignee = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Integrate OAuth 2.0 with support for Google, GitHub, and Microsoft providers.",
                            DueDate = new DateOnly(2026, 4, 15),
                            IssueNumber = 2,
                            ParentIssueId = 1,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "OAuth 2.0 Integration",
                            Type = "Story",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Assignee = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure OAuth credentials and callback URLs.",
                            DueDate = new DateOnly(2026, 4, 8),
                            IssueNumber = 3,
                            ParentIssueId = 2,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Closed",
                            Title = "Set up OAuth provider config",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handle silent token refresh before expiry.",
                            DueDate = new DateOnly(2026, 4, 12),
                            IssueNumber = 4,
                            ParentIssueId = 2,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Implement token refresh logic",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "After page reload the refresh token is lost from session storage.",
                            DueDate = new DateOnly(2026, 4, 9),
                            IssueNumber = 5,
                            ParentIssueId = 2,
                            Priority = "Critical",
                            ProjectId = 1,
                            Status = "Blocked",
                            Title = "Refresh token not persisted on reload",
                            Type = "Bug",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement granular RBAC with admin, member, and viewer roles.",
                            DueDate = new DateOnly(2026, 4, 25),
                            IssueNumber = 6,
                            ParentIssueId = 1,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Role-Based Access Control",
                            Type = "Story",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document all permissions per role.",
                            DueDate = new DateOnly(2026, 4, 18),
                            IssueNumber = 7,
                            ParentIssueId = 6,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Define permission matrix",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Assignee = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add route guards based on user role.",
                            DueDate = new DateOnly(2026, 4, 22),
                            IssueNumber = 8,
                            ParentIssueId = 6,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Middleware guard implementation",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jest test coverage for all middleware guards.",
                            DueDate = new DateOnly(2026, 4, 24),
                            IssueNumber = 9,
                            ParentIssueId = 6,
                            Priority = "Low",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Write unit tests for guards",
                            Type = "Subtask",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Log all authentication events to the audit trail.",
                            DueDate = new DateOnly(2026, 4, 20),
                            IssueNumber = 10,
                            ParentIssueId = 1,
                            Priority = "Low",
                            ProjectId = 1,
                            Status = "Review",
                            Title = "Audit login event logging",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build the main analytics dashboard with real-time charts, KPI widgets, and custom date ranges.",
                            DueDate = new DateOnly(2026, 5, 15),
                            IssueNumber = 11,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Dashboard & Analytics",
                            Type = "Epic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Draggable, configurable widget grid for key metrics.",
                            DueDate = new DateOnly(2026, 5, 5),
                            IssueNumber = 12,
                            ParentIssueId = 11,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "KPI Widget System",
                            Type = "Story",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement responsive drag-and-drop grid.",
                            DueDate = new DateOnly(2026, 4, 28),
                            IssueNumber = 13,
                            ParentIssueId = 12,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Grid layout engine",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Connect widget slots to API data sources.",
                            DueDate = new DateOnly(2026, 5, 2),
                            IssueNumber = 14,
                            ParentIssueId = 12,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Widget data connectors",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "At tablet breakpoint widgets overlap instead of reflow.",
                            DueDate = new DateOnly(2026, 4, 26),
                            IssueNumber = 15,
                            ParentIssueId = 12,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Widget overlap on resize at 768px",
                            Type = "Bug",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Line, bar, and pie charts for all tracked metrics.",
                            DueDate = new DateOnly(2026, 5, 12),
                            IssueNumber = 16,
                            ParentIssueId = 11,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Charts & Visualizations",
                            Type = "Story",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Evaluated and integrated Recharts.",
                            DueDate = new DateOnly(2026, 4, 14),
                            IssueNumber = 17,
                            ParentIssueId = 16,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Closed",
                            Title = "Integrate charting library",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Custom date picker with presets (7d, 30d, custom).",
                            DueDate = new DateOnly(2026, 4, 22),
                            IssueNumber = 18,
                            ParentIssueId = 16,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Review",
                            Title = "Date range picker component",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Address P95 latency regressions and scale the backend for 10x traffic.",
                            DueDate = new DateOnly(2026, 4, 18),
                            IssueNumber = 19,
                            Priority = "Critical",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Performance & Infrastructure",
                            Type = "Epic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profile slow queries with EXPLAIN ANALYZE.",
                            DueDate = new DateOnly(2026, 4, 10),
                            IssueNumber = 20,
                            ParentIssueId = 19,
                            Priority = "Critical",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Database query profiling",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Assignee = "MJ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Projects list endpoint triggers 40+ individual queries due to missing eager loading.",
                            DueDate = new DateOnly(2026, 4, 11),
                            IssueNumber = 21,
                            ParentIssueId = 19,
                            Priority = "Critical",
                            ProjectId = 1,
                            Status = "Blocked",
                            Title = "N+1 query on /api/projects",
                            Type = "Bug",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Assignee = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cache frequently-read data with 60s TTL.",
                            DueDate = new DateOnly(2026, 4, 16),
                            IssueNumber = 22,
                            ParentIssueId = 19,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Add Redis caching layer",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Assignee = "DT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure CloudFront distribution for JS/CSS/images.",
                            DueDate = new DateOnly(2026, 4, 5),
                            IssueNumber = 23,
                            ParentIssueId = 19,
                            Priority = "Low",
                            ProjectId = 1,
                            Status = "Closed",
                            Title = "CDN setup for static assets",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ensure full mobile support across all screens from 320px to 1440px.",
                            DueDate = new DateOnly(2026, 5, 30),
                            IssueNumber = 24,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Mobile Responsiveness",
                            Type = "Epic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "List all components that break below 768px.",
                            DueDate = new DateOnly(2026, 5, 10),
                            IssueNumber = 25,
                            ParentIssueId = 24,
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Audit existing breakpoints",
                            Type = "Task",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Assignee = "LK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The hamburger menu fails to open on iPhone 14 Safari 17.",
                            DueDate = new DateOnly(2026, 5, 8),
                            IssueNumber = 26,
                            ParentIssueId = 24,
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Open",
                            Title = "Navbar collapses incorrectly on iOS Safari",
                            Type = "Bug",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TreeTrack.Server.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "PA",
                            Name = "ProjectAlpha"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeTrack.Server.Models.Issue", b =>
                {
                    b.HasOne("TreeTrack.Server.Models.Issue", "ParentIssue")
                        .WithMany("Children")
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TreeTrack.Server.Models.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentIssue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TreeTrack.Server.Models.Issue", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TreeTrack.Server.Models.Project", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
